### ISSUE TITLE
Styling: use CoreUI theming

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/MicrobiomeWebsite#25]
Add CoreUI theming. 

Proposed colors:
- primary: mutedBlue 600
- secondary: mutedRed 500

**Comment by asizemore** [comment]
Closed with #24

**Comment by SheenaTomko** [comment]
@asizemore this is already assigned to you and was moved to "Ready for testing"

**Comment by asizemore** [comment]
Thanks @SheenaTomko !

@dpbisme assigning to you. The best way to QA this ticket is to check the colors of buttons and button text on the feature site.

**Comment by dpbisme** [comment]
Looks good to me!

**Comment by dpbisme** [comment]
No complaints about this styling.
