### ISSUE TITLE
Add site search for mbio

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/MicrobiomeWebsite#34]

**Comment by dmfalke** [comment]
Will this differ from what ClinEpiDB is doing?

cc @asizemore @dpbisme

**Comment by asizemore** [comment]
@dmfalke I don't think so. Just the same is great! Given everything else we're working on right now, this is pretty low priority for a while.

**Comment by asizemore** [comment]
@dpbisme i have site search on the agenda for our next mbio eda planning meeting. It'd be great to confirm that mbio's site search can be the same as clinepis (in terms of data searched and presentation).

**Comment by asizemore** [comment]
Confirmed that mbio's site search should be the same as clinepi's

**Comment by asizemore** [comment]
Plan is for john I to make the necessary files as long as it's easy.

**Comment by asizemore** [comment]
Update - John I is making good progress and hoping to be done by the end of the week.

**Comment by dmfalke** [comment]
Site search is now available on the beta and feature sites.

**Comment by asizemore** [comment]
WOW thank you @dmfalke !!

**Comment by asizemore** [comment]
assigning to @dpbisme for QA.
@SheenaTomko or @danicahelb would one of you or the clinepi team mind taking a brief look as well? Since you're familiar with how clinepi's works, it'd be helpful to have your eyes on how site search works for mbio as well.

**Comment by SheenaTomko** [comment]
This looks good now! Site search on mbio and clinepi return only their respective results
