### ISSUE TITLE
Mbio eda: update homepage for eda

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/MicrobiomeWebsite#39]
Update the homepage so that we no longer have the explore visualizations row, and change the example searches row text to match clinepi's example analyses row.

**Comment by asizemore** [comment]
Closed with commit f1449cfc7c1e92b0060e0a0eab46880ccc3f18dc

Deployed to feature.mbio. Ready for QA

**Comment by SheenaTomko** [comment]
Looks good!
