### ISSUE TITLE
mbio: scatterplot with data but no points

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/MicrobiomeWebsite#52]
From beta site:
<img width="1763" alt="Screen Shot 2022-12-23 at 11 19 08 AM" src="https://user-images.githubusercontent.com/11710234/209366677-2f165170-4a76-48df-9231-8c701f48f224.png">

This is a funny scatterplot. According to the response there should be 267 points, but we see none on the plot. Even switching to the Auto-Zoom revealed no points. The hunt for the missing points is on!

**Comment by moontrip** [comment]
@asizemore my two cents: Please update your main (git pull and yarn install) and see if it works. There was an error one or two days ago that the scatterplot didn’t show markers but it was fixed: it was because of marker opacity related stuff. Wish this is the case!

**Comment by asizemore** [comment]
I'll check! Thanks @moontrip !

**Comment by asizemore** [comment]
@moontrip you're right it looks to be the opacity issue you mentioned. I updated my local repo and all worked! Could you please point me to the commits or PR that fixed the issue? Unfortunately the mbio beta site got this bug so I'm hoping we can update the beta site with the fix. Thanks!

**Comment by moontrip** [comment]
Hi @asizemore Sounds great! The fix was made at web-components (https://github.com/VEuPathDB/web-components/pull/433): for reference, its version up at web-eda was made at https://github.com/VEuPathDB/web-eda/pull/1540. 

Actually scatterplot opacity PR at web-eda is not merged yet which was one of the reasons of the bug.

A bit late but Happy New Year!

**Comment by dmfalke** [comment]
I've downgraded the versions of @veupathdb/eda and @veupathdb/components used by MicrobiomeWebsite#api-build-61. They we mistakenly upgraded. I'm closing this issue.
